version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: rewynd
    ports:
      - "5432:5432"

  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command:
      - "--save ''"
      - "--notify-keyspace-events 'AKE'"

  worker:
    image: rewynd-local-worker:latest
    restart: always
    volumes:
      - "/media/Media:/media/Media"
    environment:
      DISABLE_API: true
      POSTGRES_HOSTNAME: db
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: rewynd
      POSTGRES_PORT: 5432
      REDIS_HOSTNAME: cache
      REDIS_PORT: 6379

  api:
    image: rewynd-api-local:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      DISABLE_WORKER: true
      POSTGRES_HOSTNAME: db
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: rewynd
      POSTGRES_PORT: 5432
      REDIS_HOSTNAME: cache
      REDIS_PORT: 6379
